name: main
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_icons: '^0.9.2'

flutter_icons:
  ios: true
  android: true
  image_path_ios: 'assets/icons/icon.png'
  image_path_android: 'assets/icons/icon.png'
  adaptive_icon_background: 'assets/icons/background.png'
  adaptive_icon_foreground: 'assets/icons/foreground.png'

flutter:
  uses-material-design: true

  assets:
    - assets/images/
  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-Regular.ttf
